aws_region            = "us-east-1"
site_project_name     = "testproject"
price_class           = "PriceClass_100"
local_static_asset_directory = "static_site"
oai_identity_comment  = "testprojectoai"